
export { XyoNearbyDevices } from './devices/xyo-nearby-devices'
export { IXyoAdvertisement } from './interfaces/xyo-advertisement'
export { IXyoBluetoothDevice } from './interfaces/xyo-bluetooth-device'
export { IXyoCharacteristic } from './interfaces/xyo-characteristic'
export { IXyoDescriptor } from './interfaces/xyo-descriptor'
export { IXyoIBeacon } from './interfaces/xyo-ibeacon'
export { IXyoScann } from './interfaces/xyo-scan'
export { IXyoService } from './interfaces/xyo-service'
export { XyoPipeClient } from './devices/xyo-pipe-client'
