port: 11000
graphql: 11001
data: ./archivist-db
nodeName: Development Archivist
isPublic: true
ipOverride: 127.0.0.1
sql:
  host: 127.0.0.1
  port: 3306
  user: admin
  password: password
  database: Xyo