/*
 * @Author: XY | The Findables Company <ryanxyo>
 * @Date:   Wednesday, 13th February 2019 10:28:51 am
 * @Email:  developer@xyfindables.com
 * @Filename: resolvers-enum
 * @Last modified by: ryanxyo
 * @Last modified time: Wednesday, 13th February 2019 1:33:59 pm
 * @License: All Rights Reserved
 * @Copyright: Copyright XY | The Findables Company
 */

export enum IResolvers {
  SIGNERS = 'SIGNERS',
  NETWORK = 'NETWORK',
  PEER_CONNECTION_DELEGATE = 'PEER_CONNECTION_DELEGATE',
  PEER_TRANSPORT = 'PEER_TRANSPORT',
  NODE_RUNNER_DELEGATE = 'NODE_RUNNER_DELEGATE',
  NODE_NETWORK = 'NODE_NETWORK',
  P2P_SERVICE = 'P2P_SERVICE',
  DISCOVERY_NETWORK = 'DISCOVERY_NETWORK',
  SERIALIZATION_SERVICE = 'SERIALIZATION_SERVICE',
  HASH_PROVIDER = 'HASH_PROVIDER',
  ORIGIN_CHAIN_REPOSITORY = 'ORIGIN_CHAIN_REPOSITORY',
  ORIGIN_BLOCK_REPOSITORY = 'ORIGIN_BLOCK_REPOSITORY',
  BOUND_WITNESS_PAYLOAD_PROVIDER = 'BOUND_WITNESS_PAYLOAD_PROVIDER',
  BOUND_WITNESS_SUCCESS_LISTENER = 'BOUND_WITNESS_SUCCESS_LISTENER',
  BOUND_WITNESS_VALIDATOR = 'BOUND_WITNESS_VALIDATOR',
  TRANSACTION_REPOSITORY = 'TRANSACTION_REPOSITORY',
  NETWORK_PROCEDURE_CATALOGUE = 'NETWORK_PROCEDURE_CATALOGUE'
}
