/*
 * @Author: XY | The Findables Company <ryanxyo>
 * @Date:   Monday, 3rd December 2018 1:54:01 pm
 * @Email:  developer@xyfindables.com
 * @Filename: schema.sql
 * @Last modified by: ryanxyo
 * @Last modified time: Monday, 3rd December 2018 1:54:29 pm
 * @License: All Rights Reserved
 * @Copyright: Copyright XY | The Findables Company
 */

-- MySQL Script generated by MySQL Workbench
-- Thu Oct 25 11:13:59 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='';

-- -----------------------------------------------------
-- Schema Xyo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Xyo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Xyo` DEFAULT CHARACTER SET utf8 ;
USE `Xyo` ;

-- -----------------------------------------------------
-- Table `Xyo`.`OriginBlocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Xyo`.`OriginBlocks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `signedHash` VARCHAR(128) NOT NULL,
  `signedBytes` BLOB NOT NULL,
  `bytes` BLOB NOT NULL,
  `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `bridgedFromBlock` VARCHAR(128) NULL,
  `meta` BLOB NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `signedHash_UNIQUE` (`signedHash`(128)),
  INDEX `bridgedFromBlock_INDEX` (`bridgedFromBlock`(128))
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Xyo`.`PublicKeyGroups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Xyo`.`PublicKeyGroups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Xyo`.`PublicKeys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Xyo`.`PublicKeys` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `publicKeyGroupId` INT NOT NULL,
  `key` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`),
  `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX `key_UNIQUE` (`key`(128)),
  CONSTRAINT `fk_PublicKeys_PublicKeyGroups`
    FOREIGN KEY (`publicKeyGroupId`)
    REFERENCES `Xyo`.`PublicKeyGroups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Xyo`.`OriginBlockParties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Xyo`.`OriginBlockParties` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `originBlockId` INT NOT NULL,
  `nextPublicKeyId` INT NULL,
  `positionalIndex` INT UNSIGNED NOT NULL,
  `blockIndex` INT UNSIGNED NOT NULL,
  `bridgeHashSet` BLOB NULL,
  `previousOriginBlockPartyId` INT NULL,
  `previousOriginBlockHash` VARCHAR(128) NULL,
  `payloadBytes` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_OriginBlockParties_OriginBlocks1_idx` (`originBlockId` ASC),
  INDEX `fk_OriginBlockParties_PublicKeys1_idx` (`nextPublicKeyId` ASC),
  INDEX `fk_OriginBlockParties_OriginBlockParties1_idx` (`previousOriginBlockPartyId` ASC),
  INDEX `previousOriginBlockHash_UNIQUE` (`previousOriginBlockHash`(128)),
  INDEX `OriginBlockParties_index` (`blockIndex` ASC),
  CONSTRAINT `fk_OriginBlockParties_OriginBlocks1`
    FOREIGN KEY (`originBlockId`)
    REFERENCES `Xyo`.`OriginBlocks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OriginBlockParties_PublicKeys1`
    FOREIGN KEY (`nextPublicKeyId`)
    REFERENCES `Xyo`.`PublicKeys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OriginBlockParties_OriginBlockParties1`
    FOREIGN KEY (`previousOriginBlockPartyId`)
    REFERENCES `Xyo`.`OriginBlockParties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Xyo`.`KeySignatures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Xyo`.`KeySignatures` (
  `originBlockPartyId` INT NOT NULL,
  `publicKeyId` INT NOT NULL,
  `signature` VARCHAR(1024) NOT NULL,
  `positionalIndex` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`originBlockPartyId`, `publicKeyId`),
  INDEX `fk_OriginBlockParties_has_PublicKeys_PublicKeys1_idx` (`publicKeyId` ASC),
  INDEX `fk_OriginBlockParties_has_PublicKeys_OriginBlockParties1_idx` (`originBlockPartyId` ASC),
  CONSTRAINT `fk_OriginBlockParties_has_PublicKeys_OriginBlockParties1`
    FOREIGN KEY (`originBlockPartyId`)
    REFERENCES `Xyo`.`OriginBlockParties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OriginBlockParties_has_PublicKeys_PublicKeys1`
    FOREIGN KEY (`publicKeyId`)
    REFERENCES `Xyo`.`PublicKeys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Xyo`.`PayloadItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Xyo`.`PayloadItems` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `originBlockPartyId` INT NOT NULL,
  `isSigned` TINYINT(1) NOT NULL,
  `schemaObjectId` TINYINT(3) NOT NULL,
  `bytes` VARCHAR(8192) NOT NULL,
  `positionalIndex` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PayloadItems_OriginBlockParties1_idx` (`originBlockPartyId` ASC),
  CONSTRAINT `fk_PayloadItems_OriginBlockParties1`
    FOREIGN KEY (`originBlockPartyId`)
    REFERENCES `Xyo`.`OriginBlockParties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
